# Use an official Python image from Docker Hub
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy all files from current directory to /app
COPY . .

# Set the command to run the app
CMD ["python", "app.py"]
